version: '3'

services:
  dockerapp:
    image: dockerapp:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_dockerapp$
    volumes:
      - C:\z_git\CSharp7-and-.NET-Core-2.0-Blueprints\DockerApp\DockerApp:C:\app
      - C:\Users\Dirk Strauss\onecoremsvsmon:C:\remote_debugger:ro
#$nuget_volume_mapping_dockerapp$
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_dockerapp$ bin\\Debug\\netcoreapp2.0\\DockerApp.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"
